version: "3.8"

services:
  web:
    build: .
    container_name: "fastapi_web_server"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - mongo
    env_file:
      - .env
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: fastapi_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mongo:
    image: mongo:6.0
    container_name: fastapi_mongo_db
    restart: always
    environment:
      MONGO_INITDB_DATABASE: fastapi_mongo_db
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  postgres_data:
  mongo_data:
